"use client";

import React, { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import {
    FileText,
    Database,
    ShieldCheck,
    BarChart3,
    ListTree,
    Search,
    CheckCircle2,
    ArrowRight,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { cn } from "@/shared/utils/cn";
import styles from "./AuditShowcase.module.scss";

interface AuditShowcaseProps {
    caseStudyFiles: Record<string, string>;
}

const FILE_ICONS: Record<string, LucideIcon> = {
    "SUMMARY.md": ShieldCheck,
    "UI_UX_AUDIT.md": Search,
    "COMPONENT_MAP.md": ListTree,
    "UX_HEURISTICS.md": BarChart3,
    "VISUAL_HIERARCHY.md": FileText,
    "audit.json": Database,
};

export const AuditShowcase = ({ caseStudyFiles }: AuditShowcaseProps) => {
    const fileNames = Object.keys(FILE_ICONS).filter((name) => caseStudyFiles[name]);
    const [activeFile, setActiveFile] = useState<string>(fileNames[0] || "SUMMARY.md");

    if (!caseStudyFiles || fileNames.length === 0) return null;

    const renderContent = () => {
        if (activeFile.endsWith(".json")) {
            return (
                <div className={styles.jsonBlock}>
                    {caseStudyFiles[activeFile]}
                </div>
            );
        }

        const lines = caseStudyFiles[activeFile]?.split("\n") ?? [];
        return lines.map((line, i) => {
            if (line.startsWith("# "))
                return (
                    <h1 key={i} className={styles.contentH1}>
                        {line.replace("# ", "")}
                    </h1>
                );
            if (line.startsWith("## "))
                return (
                    <h2 key={i} className={styles.contentH2}>
                        <div className={styles.contentH2Dot} />
                        {line.replace("## ", "")}
                    </h2>
                );
            if (line.startsWith("### "))
                return (
                    <h3 key={i} className={styles.contentH3}>
                        {line.replace("### ", "")}
                    </h3>
                );
            if (line.startsWith("**"))
                return (
                    <p key={i} className={styles.contentBold}>
                        {line}
                    </p>
                );
            if (line.startsWith("- "))
                return (
                    <div key={i} className={styles.contentLi}>
                        <div className={styles.contentLiDot} />
                        {line.replace("- ", "")}
                    </div>
                );
            if (line.startsWith("|"))
                return (
                    <div key={i} className={styles.contentTable}>
                        {line}
                    </div>
                );
            if (line.trim() === "")
                return <div key={i} className={styles.contentSpacer} />;
            return (
                <p key={i} className={styles.contentP}>
                    {line}
                </p>
            );
        });
    };

    return (
        <section className={styles.root}>
            <div className={styles.container}>
                <div className={styles.inner}>
                    <div className={styles.topSection}>
                        <div className={cn(styles.topContent, styles.spaceY6)}>
                            <div className={styles.badge}>
                                CASE STUDY: PLATFORM DEVELOPMENT BOARD
                            </div>

                            <h2 className={styles.title}>
                                Deep UI/UX <br />
                                <span className={styles.titleAccent}>Audit Showcase</span>
                            </h2>

                            <p className={styles.description}>
                                This is a real report generated by Iceberg Audit AI. We
                                analyzed 6 major vectors of UI quality to help the
                                developers identify critical bottlenecks.
                            </p>

                            <div className={styles.checkRow}>
                                <div className={styles.checkItem}>
                                    <CheckCircle2 className={styles.checkIcon} />
                                    6 Comprehensive Files
                                </div>
                                <div className={styles.checkItem}>
                                    <CheckCircle2 className={styles.checkIcon} />
                                    100% Automated Analysis
                                </div>
                            </div>
                        </div>

                        <div className={styles.imageWrap}>
                            <div className={styles.imageGlow} />
                            <div className={styles.imageCard}>
                                <Image
                                    src="/assets/audit/photo_2026-01-24_12-37-01.jpg"
                                    alt="Platform Board UI"
                                    width={800}
                                    height={400}
                                    className={styles.image}
                                />
                                <div className={styles.imageOverlay}>
                                    <div>
                                        <p className={styles.imageCaptionLabel}>
                                            Source Image
                                        </p>
                                        <p className={styles.imageCaption}>
                                            Jira-style Kanban Board
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className={styles.reader}>
                        <div className={styles.tabs}>
                            {fileNames.map((fileName) => {
                                const Icon = FILE_ICONS[fileName];
                                const isActive = activeFile === fileName;
                                return (
                                    <button
                                        key={fileName}
                                        type="button"
                                        onClick={() => setActiveFile(fileName)}
                                        className={cn(
                                            styles.tab,
                                            isActive ? styles.tabActive : styles.tabInactive
                                        )}
                                    >
                                        <Icon className={styles.tabIcon} />
                                        {fileName}
                                    </button>
                                );
                            })}
                        </div>

                        <div
                            className={cn(styles.content, styles.customScrollbar)}
                        >
                            <AnimatePresence mode="wait">
                                <motion.div
                                    key={activeFile}
                                    initial={{ opacity: 0, scale: 0.99 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 0.99 }}
                                    transition={{ duration: 0.2 }}
                                    className={styles.contentInner}
                                >
                                    {renderContent()}
                                </motion.div>
                            </AnimatePresence>
                        </div>

                        <div className={styles.footer}>
                            <div className={styles.footerText}>
                                <h4 className={styles.footerTitle}>
                                    This is a showcase of the Iceberg Full Audit.
                                </h4>
                                <p className={styles.footerDesc}>
                                    You will receive these exact 6 files for your UI in a
                                    single ZIP.
                                </p>
                            </div>
                            <button
                                type="button"
                                onClick={() =>
                                    window.scrollTo({ top: 0, behavior: "smooth" })
                                }
                                className={styles.ctaButton}
                            >
                                Test Your Own Site
                                <ArrowRight className={styles.ctaIcon} />
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};
